### ISSUE TITLE
Project Is Excluded from HckroberFest 2021

### ISSUE THREAD

**Issue by hadviad0x15** [aritraroy24/HACKTOBERFEST2021_INSPIRATION#83]
Any suggestion

**Comment by aritraroy24** [comment]
@hadviad0x15  Is it? My [other repo](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN) has been excluded by Hacktoberfest. But I'm not sure if this has been excluded. I have completed my Hacktoberfest challenge from my other GitHub account and sent a PR to this repo and this has been accepted. See below - 
![image](https://user-images.githubusercontent.com/65696941/139248208-b90b189a-117b-498a-be8a-80b779c1a225.png)

**So, please be sure if this repo has been excluded now and send me a screenshot of that.** and if this has been excluded then it can't be included in **Hacktoberfest 2021** again.

**Comment by hadviad0x15** [comment]
Hi, Greeting of the day. Below you can see the screenshot for the same. Hope it helps. @aritraroy24 
![image](https://user-images.githubusercontent.com/91744207/139430280-55d8deaf-5d76-48ff-bf7f-e452fcbee65b.png)

**Comment by hadviad0x15** [comment]
Also I would like to thankyou for making this task beginners friendly. As I was participating  for the first time it help me a lot but unfortunately the project got excluded. Hope next year we work together on such beginner friendly issues. @aritraroy24

**Comment by aritraroy24** [comment]
@hadviad0x15 oh man...bad luck buddy... actually, due to massive engagement in this repo, hacktoberfest thought all the PRs to this repo were spam...sorry for you...I hope you finish your hacktoberfest challenge...🤗
